### ISSUE TITLE
Developement versione fill up log with exceptions

### ISSUE THREAD

**Issue by DreadTank27** [andrepl/BuildInABox#19]
Thge title says all, except that those exceptions are all PlayerInteractEvent

**Comment by andrepl** [comment]
can you pastebin one of them please? I'm running the latest snapshot w/ no errors.  also include your config.yml

**Comment by DreadTank27** [comment]
Sure.
Server.log : http://pastebin.com/RGn27BzN
Config.yml : http://pastebin.com/ysXesuWz

**Comment by andrepl** [comment]
Thanks!

I just pushed a new development build (#130) that hopefully fixes the problem.  please let me know if it does.

**Comment by DreadTank27** [comment]
Yeah, now it's all ok!
Thank you very much man!

**Comment by andrepl** [comment]
Thank you for the feedback :)
