### ISSUE TITLE
compatible with ss ?

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#21]
i have this plugin, which is showing who is online.
first line of a sign is [ss]
second line his name.

link to the plugin http://dev.bukkit.org/bukkit-mods/status-sign/

do you have any way to provide his name on this sign at biab?
I plan to give away the house to anyone, and do not know for a start who is getting it.
So i might need to contact the author of that sign also, but do you have any variables included?

**Comment by andrepl** [comment]
I looked at the plugin, but I don't think this will be possible without adding a a lot of extra work to the already heavy building task, so I'm not going to accept this one, sorry :(
