### ISSUE TITLE
Fails to save large schematics with no warning

### ISSUE THREAD

**Issue by andrepl** [andrepl/BuildInABox#24]
after attempting to save a large schematic, the user got no feedback and the enderchest behaved like a normal enderchest.  

@fungreenfox is the schematic that this happens with already uploaded somewhere i can test with?

**Comment by fungreenfox** [comment]
I have made a WE schematic of a building, i think is small enough and worthy for a biab box, but i can't get it saved. It turns to a normal box, not saved. This schematic has a 10x10 basement.
www.mcraft.dk/downloads/biab/villasjov.schematic
Also next one, i cant save it too.
www.mcraft.dk/downloads/biab/strandvilla.schematic

**Comment by andrepl** [comment]
fixed as of https://github.com/andrepl/Schematica/commit/2d3f63211ff9b7f9e1790111db6614cf0682f84d
