### ISSUE TITLE
plugin kicks users for building straight up

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#25]
A plugin (made on my request), is kicking users trying to spawn a biab box.
You know our Blacksmith from earlier, and this is the objekt taken for building straight up.
I don't know who will be able to fix this, but http://dev.bukkit.org/bukkit-plugins/nopillar/#comments is build very fast, just for the sake of use.
The idea is only to kick people building straight upwards, with no blocks beside, making it a 1x1 tower. I have informed the author of this plugin.
The only thing i can currently do, is bypassing the users with permission. This is not the estimate solution to this.

**Comment by andrepl** [comment]
Sorry, I can't provide support for an "All Rights Reserved" plugin.  I'm not allowed to see the source code, so I won't waste my time troubleshooting it, very sorry, but I have a strict personal code about such software.

That being said, it's NoPillar being far too loose with its definition of pillaring.  They make no effort to check who placed the blocks beneath, or when they were placed. it only checks if you are placing a block on top of a pillar, which happens many times over the course of building a house, with or without biab.
