### ISSUE TITLE
Noted Issues

### ISSUE THREAD

**Issue by SonarBeserk** [andrepl/BuildInABox#3]
Version: 0.1.7-SNAPSHOT

Issue 1: Error when trying to make a house build that doesnt have the space
http://pastie.org/7982246

Steps to reproduce:
1 place a plan in too small an area
2 confirm the house
3 let it attempt to constuct
4 errors when the ender chest is removed

Issue 2: http://pastie.org/7982263 Blocks left when building fails

Sometimes when such as Issue 1 occurs it partially places blocks and leaves them

Steps to reproduce:
1 try fail placement
2 observe left blocks

Issue 3: Players can spam the build which could cause terrible lag

Steps to reproduce:
1 place a plan
2 while the preview is going spam the build
3 watch as your build spam builds and places even when blocks are already placed, basicly queue spam.

**Comment by andrepl** [comment]
http://mcgitlab.norcode.com:8081/job/BuildInABox/88/

I think this build will fix all 3 issues.

**Comment by SonarBeserk** [comment]
http://pastie.org/7982414 is still happening if the player cant build in an area

**Comment by SonarBeserk** [comment]
I noticed when I let a box build then restarted the server that it didnt fix the area it was before. It does that if the wasnt a restart but there was.

**Comment by SonarBeserk** [comment]
When i said about the thievery i mean if you couldnt build in an area the BIAB chests would still be taken.

**Comment by SonarBeserk** [comment]
http://pastie.org/7982496 Found this, happens occasionally during building.

**Comment by andrepl** [comment]
I knew what you meant by thievery, is it still being taken though? the last error will be fixed when my work on the noworldedit branch is complete, should be tonight at some point, then I'd like to get some feedback on the development builds before doing a new release.

**Comment by andrepl** [comment]
the 0.2.0 snapshots are fairly functional now, I did a test with grief prevention and no enderchests were eaten. I'm going to close this ticket to keep things organized, report any issues against 0.2.0-SNAPSHOT as new new issues.
Latest stable build as of this writing is here: http://mcgitlab.norcode.com:8081/job/BuildInABox/99/com.norcode.bukkit.buildinabox$BuildInABox/

that will probably be merged into the master branch and released on dev.bukkit.org after a bit more testing, any feedback is appreciated.
