### ISSUE TITLE
Creation issue

### ISSUE THREAD

**Issue by Spawnatron** [andrepl/BuildInABox#37]
i just recently downloaded Build-In-A-Box because i used to play on a server that had it and i kinda liked it. after downloading and setting up a hamachi server to play with it i read the instructions on the buckit page from top to bottom, in the test server i made a simple basic tent and i set down an enderchest like it said. i then used the golden hoe to select 2 corners i selected 1 on the floor and 1 diagonally up in the air to get the full build. after selecting i did /biab save tent 
just like the person in the video did but after pressing enter it said for me "now use the selection tool to choose an ender chest to save it in" and so i right clicked and nothing happened and in /biab list 
it was empty so i tried left clicking and again nothing happened please reply back soon im interested in using it on my server when i find out why BIAB is not working for me....

**Comment by andrepl** [comment]
Did you use the release on bukkitdev? that's a known issue with that version you have to use the development builds. sorry about the confusion.

**Comment by Spawnatron** [comment]
What do you mean development builds the only place i can find Build in a Box is on BuckitDev

**Comment by Spawnatron** [comment]
a link would be helpful

**Comment by andrepl** [comment]
The link is on the bukkitdev page near the bottom under "Source code and development builds"
Here's the link:

http://mcgitlab.norcode.com:8081/job/BuildInABox/lastSuccessfulBuild/com.norcode.bukkit.buildinabox$BuildInABox/

**Comment by BigRedWolfy** [comment]
the development build link doesn't exist
can you just give us a .jar file that would work with the current minecraft 1.7.9

**Comment by andrepl** [comment]
There is no build that will work on 1.7.9. This plugin has been abandoned.  It's too much work to maintain in it's current state.  I won't be doing any updates to the existing code, but I _might_ do a complete rewrite after 1.8 lands and bukkit has time to catch up.
