### ISSUE TITLE
placed iron doors are not placed as double doors. 

### ISSUE THREAD

**Issue by SonarBeserk** [andrepl/BuildInABox#8]
wooden doors do not face this issue while iron doors do.

**Comment by andrepl** [comment]
This is yet another "i can't reproduce' situation. I've tried a wall with single and double iron doors, saved from a north/south orientation and from east/west, and pasted in all 4 orientations, everything came out correctly.  

Is there any possiblity that this is another instance of the auto-updater somehow accidentally downgrading you to 0.1.5 without your knowledge?  That's another issues I can't reproduce but at least it's only one :)

**Comment by SonarBeserk** [comment]
i recommend you change the default for the updater to notify-only

**Comment by andrepl** [comment]
done. was that actually the problem?

**Comment by SonarBeserk** [comment]
yup the auto updater is the source of the problem
