### ISSUE TITLE
north and south walls are not being removed

### ISSUE THREAD

**Issue by SonarBeserk** [andrepl/BuildInABox#9]
no errors but the walls don't get removed

**Comment by andrepl** [comment]
does this happen with newly created schematics or only pre-existing ones? I can't reproduce this problem, is there anywhere you can upload the particular schematic if it's only one?

**Comment by SonarBeserk** [comment]
plans.yml

awesome:
  name: awesome
  display-name: awesome
  filename: awesome.schematic
  description: []

**Comment by SonarBeserk** [comment]
the schematic used may be found at https://www.dropbox.com/s/tvqu6lhu7y5gszi/awesome.schematic

**Comment by SonarBeserk** [comment]
i made this schematic on 2.0

**Comment by andrepl** [comment]
how about chests.yml can I see that too please?

**Comment by SonarBeserk** [comment]
hmmm issue seems to source from the auto updater

**Comment by andrepl** [comment]
That schematic works great for me, build & pick up both go without a hitch.

**Comment by andrepl** [comment]
yay

**Comment by andrepl** [comment]
This just happened to me with your schematic and 0.2.0, but only from one angle, its a problem with the enderchest, it confuses your 2nd normal enderchest with the special one.

**Comment by SonarBeserk** [comment]
yeah that is something to beware of. it doesnt like multiple enderchests.

**Comment by andrepl** [comment]
This should be resolved as of 113 the save command requires hitting the correct enderchest to finish the save process.
